# Generated by Django 3.2.5 on 2021-12-04 15:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
