# Generated by Django 3.2.5 on 2022-01-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_post_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desc',
        ),
    ]
