# Generated by Django 3.2.5 on 2022-01-28 14:02

from django.conf import settings
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0020_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(home.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
